name: 'Dockerfile Check, Build and Push'
description: 'A standard Dockerfile workflow to check the dockerfile against standards and build the image. It can also push images to docker hub.'
author: 'Deriv.com'
inputs:
  images:
    description: 'Image name'
    required: true
  push:
    description: 'Boolean to represent if we want to Push image to a Docker registry'
    required: false
    default: 'false'
  registry:
    description: 'Server address of Docker registry'
    required: false
  username:
    description: 'Username used to log against the Docker registry'
    required: false
  password:
    description: 'Password or personal access token used to log against the Docker registry'
    required: false
outputs:
  imageid:
    description: 'Image ID'
    value: ${{ steps.build.imageid }}
runs:
  using: "composite"
  steps:
    - name: Linter for Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.images }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=ref,event=tag
    - name: Login to GitHub Container Registry
      if: ${{ inputs.push == 'true' }}
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Build
      id: build
      uses: docker/build-push-action@v5
      with:
        push: false
        tags: ${{ steps.meta.outputs.tags }}